
export const RECEIVE_TRAIN = 'RECEIVE_TRAIN'
export const REQUEST_TRAIN = 'REQUEST_TRAIN'
export const REQUEST_TRAIN_FAILED = 'REQUEST_TRAIN_FAILED'

export const RECEIVE_ENTITIES = 'RECEIVE_ENTITIES'
export const REQUEST_ENTITIES = 'REQUEST_ENTITIES'
export const REQUEST_ENTITIES_FAILED = 'REQUEST_ENTITIES_FAILED'


export const REQUEST_DOCUMENTS = 'REQUEST_DOCUMENTS'
export const REQUEST_DOCUMENTS_FAILED = 'REQUEST_DOCUMENTS_FAILED'
export const RECEIVE_DOCUMENTS = 'RECEIVE_DOCUMENTS'

export const SAVE_DOCUMENT = 'SAVE_DOCUMENT'
export const SAVE_DOCUMENT_FAILED = 'SAVE_DOCUMENT_FAILED'

export const NEXT_DOCUMENT = 'NEXT_DOCUMENT'
export const PREV_DOCUMENT = 'PREV_DOCUMENT'

export const CHANGE_CORPUS = 'CHANGE_CORPUS'
export const CHANGE_TAG = 'CHANGE_TAG'
